/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubsRouteImport } from './routes/subs'
import { Route as SpendsRouteImport } from './routes/spends'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as CalRouteImport } from './routes/cal'
import { Route as AiRouteImport } from './routes/ai'
import { Route as SplatRouteImport } from './routes/$'
import { Route as SignInRouteRouteImport } from './routes/sign-in/route'
import { Route as ConfigureRouteRouteImport } from './routes/configure/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as ConfigureIndexRouteImport } from './routes/configure/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as ConfigureSubscriptionsRouteImport } from './routes/configure/subscriptions'

const SubsRoute = SubsRouteImport.update({
  id: '/subs',
  path: '/subs',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendsRoute = SpendsRouteImport.update({
  id: '/spends',
  path: '/spends',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalRoute = CalRouteImport.update({
  id: '/cal',
  path: '/cal',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRouteRoute = SignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRouteRoute = ConfigureRouteRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignInRouteRoute,
} as any)
const ConfigureIndexRoute = ConfigureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfigureRouteRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRouteRoute,
} as any)
const ConfigureSubscriptionsRoute = ConfigureSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => ConfigureRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRouteRouteWithChildren
  '/sign-in': typeof SignInRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/ai': typeof AiRoute
  '/cal': typeof CalRoute
  '/onboard': typeof OnboardRoute
  '/settings': typeof SettingsRoute
  '/spends': typeof SpendsRoute
  '/subs': typeof SubsRoute
  '/configure/subscriptions': typeof ConfigureSubscriptionsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/configure/': typeof ConfigureIndexRoute
  '/sign-in/': typeof SignInIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai': typeof AiRoute
  '/cal': typeof CalRoute
  '/onboard': typeof OnboardRoute
  '/settings': typeof SettingsRoute
  '/spends': typeof SpendsRoute
  '/subs': typeof SubsRoute
  '/configure/subscriptions': typeof ConfigureSubscriptionsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/configure': typeof ConfigureIndexRoute
  '/sign-in': typeof SignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRouteRouteWithChildren
  '/sign-in': typeof SignInRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/ai': typeof AiRoute
  '/cal': typeof CalRoute
  '/onboard': typeof OnboardRoute
  '/settings': typeof SettingsRoute
  '/spends': typeof SpendsRoute
  '/subs': typeof SubsRoute
  '/configure/subscriptions': typeof ConfigureSubscriptionsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/configure/': typeof ConfigureIndexRoute
  '/sign-in/': typeof SignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configure'
    | '/sign-in'
    | '/$'
    | '/ai'
    | '/cal'
    | '/onboard'
    | '/settings'
    | '/spends'
    | '/subs'
    | '/configure/subscriptions'
    | '/sign-in/$'
    | '/configure/'
    | '/sign-in/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ai'
    | '/cal'
    | '/onboard'
    | '/settings'
    | '/spends'
    | '/subs'
    | '/configure/subscriptions'
    | '/sign-in/$'
    | '/configure'
    | '/sign-in'
  id:
    | '__root__'
    | '/'
    | '/configure'
    | '/sign-in'
    | '/$'
    | '/ai'
    | '/cal'
    | '/onboard'
    | '/settings'
    | '/spends'
    | '/subs'
    | '/configure/subscriptions'
    | '/sign-in/$'
    | '/configure/'
    | '/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigureRouteRoute: typeof ConfigureRouteRouteWithChildren
  SignInRouteRoute: typeof SignInRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AiRoute: typeof AiRoute
  CalRoute: typeof CalRoute
  OnboardRoute: typeof OnboardRoute
  SettingsRoute: typeof SettingsRoute
  SpendsRoute: typeof SpendsRoute
  SubsRoute: typeof SubsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subs': {
      id: '/subs'
      path: '/subs'
      fullPath: '/subs'
      preLoaderRoute: typeof SubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spends': {
      id: '/spends'
      path: '/spends'
      fullPath: '/spends'
      preLoaderRoute: typeof SpendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cal': {
      id: '/cal'
      path: '/cal'
      fullPath: '/cal'
      preLoaderRoute: typeof CalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof SignInRouteRoute
    }
    '/configure/': {
      id: '/configure/'
      path: '/'
      fullPath: '/configure/'
      preLoaderRoute: typeof ConfigureIndexRouteImport
      parentRoute: typeof ConfigureRouteRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRouteRoute
    }
    '/configure/subscriptions': {
      id: '/configure/subscriptions'
      path: '/subscriptions'
      fullPath: '/configure/subscriptions'
      preLoaderRoute: typeof ConfigureSubscriptionsRouteImport
      parentRoute: typeof ConfigureRouteRoute
    }
  }
}

interface ConfigureRouteRouteChildren {
  ConfigureSubscriptionsRoute: typeof ConfigureSubscriptionsRoute
  ConfigureIndexRoute: typeof ConfigureIndexRoute
}

const ConfigureRouteRouteChildren: ConfigureRouteRouteChildren = {
  ConfigureSubscriptionsRoute: ConfigureSubscriptionsRoute,
  ConfigureIndexRoute: ConfigureIndexRoute,
}

const ConfigureRouteRouteWithChildren = ConfigureRouteRoute._addFileChildren(
  ConfigureRouteRouteChildren,
)

interface SignInRouteRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
  SignInIndexRoute: typeof SignInIndexRoute
}

const SignInRouteRouteChildren: SignInRouteRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
  SignInIndexRoute: SignInIndexRoute,
}

const SignInRouteRouteWithChildren = SignInRouteRoute._addFileChildren(
  SignInRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigureRouteRoute: ConfigureRouteRouteWithChildren,
  SignInRouteRoute: SignInRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AiRoute: AiRoute,
  CalRoute: CalRoute,
  OnboardRoute: OnboardRoute,
  SettingsRoute: SettingsRoute,
  SpendsRoute: SpendsRoute,
  SubsRoute: SubsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
